name: nlp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - textacy
  - neuralcoref
  - tqdm
  - jupyterlab
  - pip
  - pip:
    - nltk
    - stanfordcorenlp==3.9.1.1
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.1.3/en_core_web_sm-2.1.0.tar.gz
